Chapter11/force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter06/force-app/main/default/objects/Driver__c/fields/FIASuperLicense__c.field-meta.xml
<CustomField>
    <fullName>FIASuperLicense__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FIA Super License</label>
    <type>Checkbox</type>
</CustomField>

Chapter07/force-app/main/default/objects/Driver__c/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <label>Short Name</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

Chapter07/force-app/main/default/classes/Drivers.cls
public inherited sharing class Drivers extends ApplicationDomain implements ComplianceService.ICompliant {
    
	public Drivers(List<Driver__c> drivers) {
		super(drivers);
	}

	/**
	 * Applies defaults when creating new Driver records
	 **/
	public override void onApplyDefaults() {
		for(Driver__c driver : (List<Driver__c>) Records) {
			if(driver.ShortName__c == null) {
				// Upper case first three letters of drivers last name
				String lastName = driver.Name.substringAfterLast(' ');
				driver.ShortName__c = lastName.left(3).toUpperCase();
			}
		}
	}

	/**
	 * Checks the Driver records for compliance with the latest rules
	 **/
	public List<ComplianceService.VerifyResult> verifyCompliance() {
		List<ComplianceService.VerifyResult> compliances = new List<ComplianceService.VerifyResult>();
		for(Driver__c driver : (List<Driver__c>) Records) {
			// Check FIA Super License compliance
			ComplianceService.VerifyResult license = new ComplianceService.VerifyResult();
			license.ComplianceCode = '4.1';
			license.RecordId = driver.Id;
			license.passed = driver.FIASuperLicense__c;
			license.failureReason = license.passed ? null : 'Driver must have a FIA Super License.';
			compliances.add(license);
		}
		return compliances;		
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable {
		public fflib_SObjectDomain construct(List<SObject> sObjectList) {
			return new Drivers(sObjectList);
		}
	}	
}