Chapter11/force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter06/force-app/main/default/objects/Driver__c/fields/FIASuperLicense__c.field-meta.xml
<CustomField>
    <fullName>FIASuperLicense__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FIA Super License</label>
    <type>Checkbox</type>
</CustomField>

Chapter10/force-app/main/default/objects/Driver__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter13/force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter08/force-app/main/default/classes/DriversSelector.cls
public inherited sharing class DriversSelector extends ApplicationSelector {
    
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Driver__c.Id,
			Driver__c.Name,
			Driver__c.FIASuperLicense__c,
			Driver__c.Team__c
		};
	}

	public Schema.SObjectType getSObjectType() {
		return Driver__c.sObjectType;
	}

	public List<Driver__c> selectById(Set<Id> ids) {
		return (List<Driver__c>) super.selectSObjectsById(ids);
	}

	public List<Driver__c> selectByTeam(Set<Id> teamIds) {
	    return (List<Driver__c>) 
	       Database.query(
	           newQueryFactory().
	               setCondition('Team__c in :teamIds').
	               toSOQL());
	}
}