Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter07/force-app/main/default/objects/Race__c/fields/FastestLapBy__c.field-meta.xml
<CustomField>
    <fullName>FastestLapBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fastest Lap By</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>FastestLaps</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter14/force-app/main/default/objects/Race__c/fields/PollPositionLapTime__c.field-meta.xml
<CustomField>
    <fullName>PollPositionLapTime__c</fullName>
    <label>Poll Position Lap Time</label>
    <summarizedField>Contestant__c.Qualification1LapTime__c</summarizedField>
    <summaryForeignKey>Contestant__c.Race__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

Chapter14/force-app/main/default/objects/Race__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter12/force-app/main/default/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Chapter11/force-app/main/default/objects/Race__c/fields/TotalDNFs__c.field-meta.xml
<CustomField>
    <fullName>TotalDNFs__c</fullName>
    <label>Total DNFs</label>
    <summaryFilterItems>
        <field>Contestant__c.DNF__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Contestant__c.Race__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Chapter03/force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter08/force-app/main/default/classes/RacesSelector.cls
public inherited sharing class RacesSelector extends ApplicationSelector {
    
	public RacesSelector() {
		super();
	}

	public RacesSelector(Boolean includeFieldSetFields) {
		super(includeFieldSetFields);
	}

    public override List<Schema.FieldSet> getSObjectFieldSetList() {
        return new List<Schema.FieldSet> { 
        	SObjectType.Race__c.FieldSets.SeasonOverview 
        };
    }

	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Race__c.Id,
			Race__c.Name,
			Race__c.Status__c,
			Race__c.Season__c,
			Race__c.FastestLapBy__c,
			Race__c.PollPositionLapTime__c,
			Race__c.TotalDNFs__c
		};
	}

	public Schema.SObjectType getSObjectType() {
		return Race__c.sObjectType;
	}

	public List<Race__c> selectById(Set<Id> raceIds) {
		return (List<Race__c>) selectSObjectsById(raceIds);
	}

	public List<Race__c> selectByIdWithContestants(Set<Id> raceIds) {
	    fflib_QueryFactory racesQueryFactory = newQueryFactory();
	    fflib_QueryFactory contestantsSubQueryFactory = 
            new ContestantsSelector().addQueryFactorySubselect(racesQueryFactory); 	    
        return (List<Race__c>) Database.query(
            racesQueryFactory.setCondition('Id in :raceIds').toSOQL());
	}
}