Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter06/force-app/main/default/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
    <type>Picklist</type>
</CustomField>

Chapter06/force-app/main/default/classes/RacesSelector.cls
public inherited sharing class RacesSelector extends fflib_SObjectSelector {
    
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Race__c.Id,
			Race__c.Name,
			Race__c.Status__c
		};
	}

	public Schema.SObjectType getSObjectType() {
		return Race__c.sObjectType;
	}

	public List<Race__c> selectById(Set<Id> raceIds) {
		return (List<Race__c>) selectSObjectsById(raceIds);
	}

	public List<Race__c> selectByIdWithContestants(Set<Id> raceIds) {
		fflib_QueryFactory racesQueryFactory = newQueryFactory();
		fflib_QueryFactory contestantsSubQueryFactory =
			new ContestantsSelector().addQueryFactorySubselect(racesQueryFactory);          
		return (List<Race__c>) Database.query(
			racesQueryFactory.setCondition('Id in :raceIds').toSOQL());
	}
}