Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter14/force-app/main/default/objects/Race__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

Chapter12/force-app/main/default/objects/Race__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Chapter14/force-app/main/default/objects/Race__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

Chapter11/force-app/main/default/classes/RaceCalendarAuraComponentController.cls
public with sharing class RaceCalendarAuraComponentController {

    /**
     * Server side controller method for the RaceCalendar Lightning Component
     **/
    @AuraEnabled
    public static RaceCalendar getRaceCalendar() {
                
        RaceCalendar calendar = new RaceCalendar();
        calendar.Remaining = new List<RaceCalendarItem>();
        calendar.Completed = new List<RaceCalendarItem>();
        for(Race__c race : new RacesSelector().selectAllForCurrentYear()) {
            RaceCalendarItem raceCalendarItem = new RaceCalendarItem();
            raceCalendarItem.Id = race.Id;
            raceCalendarItem.Name = race.Name;
            raceCalendarItem.Location = race.Location__c;
            raceCalendarItem.RaceDate = race.StartDate__c.format() + ' - ' + race.EndDate__c.format();
            raceCalendarItem.Selected = false;
            if(race.StartDate__c < System.today()) {
                calendar.Completed.add(raceCalendarItem);
            } else {
                if(calendar.Remaining.size()>0) {
                    calendar.Remaining.add(0, raceCalendarItem); 
                } else {
                    calendar.Remaining.add(raceCalendarItem);
                }                
            }
        }
        if(calendar.Remaining.size()>0) {
            calendar.Remaining[0].Selected = true;
        }
        return calendar;
    }
    
    public class RaceCalendar {
        @AuraEnabled
        public List<RaceCalendarItem> Remaining;
        @AuraEnabled
        public List<RaceCalendarItem> Completed;
    }

    public class RaceCalendarItem {
        @AuraEnabled
        public Boolean Selected;
        @AuraEnabled
        public String Id;
        @AuraEnabled
        public String Name;
        @AuraEnabled
        public String Location;
        @AuraEnabled
        public String RaceDate;
    }    
}