Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter03/force-app/main/default/objects/RaceData__c/RaceData__c.object-meta.xml
<CustomObject>
    <label>Race Data</label>
    <nameField>
        <displayFormat>RDID-{00000000}</displayFormat>
        <label>Race Data Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Race Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter09/force-app/main/default/objects/RaceData__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Data</relationshipLabel>
    <relationshipName>RaceData</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter13/force-app/main/default/classes/RaceAnalysisController.cls
public class RaceAnalysisController {
    
	private ApexPages.StandardSetController standardSetController;

	public RaceAnalysisController(ApexPages.StandardSetController standardSetController) {
		this.standardSetController = standardSetController;	
	}

	public PageReference analyizeRaceData() {
	    
		// Selected race names
		Set<String> raceNames = new Set<String>();
		for(Race__c selected : (List<Race__c>) standardSetController.getSelected())
			raceNames.add(selected.Name);

		// Query all race data for selected races
		List<RaceService.AnalysisResult> analysisResults = 
			RaceService.analizeData(raceNames);

		// Debug message
		ApexPages.addMessage(
			new ApexPages.Message(
				ApexPages.Severity.Info, 
				'Just read ' + Limits.getQueryRows() + ' rows from RaceData__c'));

		return null;
	}
}