Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter11/force-app/main/default/objects/Race__c/fields/RaceId__c.field-meta.xml
<CustomField>
    <fullName>RaceId__c</fullName>
    <label>Race Id</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

Chapter12/force-app/main/default/objects/RaceLapHistorySummary__c/RaceLapHistorySummary__c.object-meta.xml
<CustomObject>
    <label>Race Lap History Summary</label>
    <nameField>
        <displayFormat>RLHS-{00000000}</displayFormat>
        <label>Race Lap History Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Race Lap History Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter13/force-app/main/default/objects/RaceLapHistorySummary__c/fields/FastestLap__c.field-meta.xml
<CustomField>
    <fullName>FastestLap__c</fullName>
    <label>Fastest Lap</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Chapter13/force-app/main/default/objects/RaceLapHistorySummary__c/fields/FastestLapTime__c.field-meta.xml
<CustomField>
    <fullName>FastestLapTime__c</fullName>
    <label>Fastest Lap Time</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter11/force-app/main/default/objects/RaceLapHistorySummary__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Lap History Summaries</relationshipLabel>
    <relationshipName>RaceLapHistorySummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter11/force-app/main/default/objects/RaceLapHistorySummary__c/fields/RaceId__c.field-meta.xml
<CustomField>
    <fullName>RaceId__c</fullName>
    <externalId>true</externalId>
    <label>Race Id</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

Chapter11/force-app/main/default/classes/RaceLapHistorySummaries.cls
public inherited sharing class RaceLapHistorySummaries extends ApplicationDomain 
{
	public RaceLapHistorySummaries(List<RaceLapHistorySummary__c> races) {
		super(races);
	}

	/** 
	 * Format lap time and associate with a Race record (if available)
	 **/
	public override void onBeforeInsert() {

		// Build a map of applicable Races given a set of race external Ids        
		Set<String> raceExternalIds = new Set<String>();
		for(RaceLapHistorySummary__c history : (List<RaceLapHistorySummary__c>) this.Records) {
			raceExternalIds.add(history.RaceId__c);
		}

		// Calculate values for Race and Fastest Lap fields
		Map<String, Race__c> racesByExternalId = new RacesSelector().selectByExternalRaceIds(raceExternalIds);
		for(RaceLapHistorySummary__c history : (List<RaceLapHistorySummary__c>) this.Records) {
			// Resolve this manually rather than via an external lookup 
			//   (since this will fail summaries where corresponding Race records don't exist)
			Race__c race = racesByExternalId.get(history.RaceId__c);
			if(race!=null) {
				history.Race__c = race.Id;
			}
			// Format the time
			history.FastestLap__c = String.valueOf(Time.newInstance(0,0,0,Integer.valueOf(history.FastestLapTime__c)));
		}
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable {
		public fflib_SObjectDomain construct(List<SObject> sObjectList) {
			return new RaceLapHistorySummaries(sObjectList);
		}
	}		
}