Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter13/force-app/main/default/objects/RaceStatistics__c/RaceStatistics__c.object-meta.xml
<CustomObject>
    <label>Race Statistics</label>
    <nameField>
        <displayFormat>RCS-{00000000}</displayFormat>
        <label>Race Statastics  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Race Statistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter13/force-app/main/default/objects/RaceStatistics__c/fields/FastestSector1Driver__c.field-meta.xml
<CustomField>
    <fullName>FastestSector1Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sector 1 Driver</label>
    <referenceTo>Contestant__c</referenceTo>
    <relationshipLabel>Race Statistics</relationshipLabel>
    <relationshipName>RaceStatisticsFastestSector1</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter14/force-app/main/default/objects/RaceStatistics__c/fields/FastestSector1Time__c.field-meta.xml
<CustomField>
    <fullName>FastestSector1Time__c</fullName>
    <label>Sector 1 Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Chapter12/force-app/main/default/objects/RaceStatistics__c/fields/FastestSector1TimeMilliseconds__c.field-meta.xml
<CustomField>
    <fullName>FastestSector1TimeMilliseconds__c</fullName>
    <label>Sector 1 Time Milliseconds</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter13/force-app/main/default/objects/RaceStatistics__c/fields/FastestSector2Driver__c.field-meta.xml
<CustomField>
    <fullName>FastestSector2Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sector 2 Driver</label>
    <referenceTo>Contestant__c</referenceTo>
    <relationshipLabel>Race Statistics (Fastest Sector 2 Driver)</relationshipLabel>
    <relationshipName>RaceStatisticsFastestSector2</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter11/force-app/main/default/objects/RaceStatistics__c/fields/FastestSector2Time__c.field-meta.xml
<CustomField>
    <fullName>FastestSector2Time__c</fullName>
    <label>Sector 2 Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Chapter13/force-app/main/default/objects/RaceStatistics__c/fields/FastestSector2TimeMilliseconds__c.field-meta.xml
<CustomField>
    <fullName>FastestSector2TimeMilliseconds__c</fullName>
    <label>Sector 2 Time Milliseconds</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter12/force-app/main/default/objects/RaceStatistics__c/fields/FastestSector3Driver__c.field-meta.xml
<CustomField>
    <fullName>FastestSector3Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sector 3 Driver</label>
    <referenceTo>Contestant__c</referenceTo>
    <relationshipLabel>Race Statistics (Fastest Sector 3 Driver)</relationshipLabel>
    <relationshipName>RaceStatisticsFastestSector3</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter13/force-app/main/default/objects/RaceStatistics__c/fields/FastestSector3Time__c.field-meta.xml
<CustomField>
    <fullName>FastestSector3Time__c</fullName>
    <label>Sector 3 Time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Chapter14/force-app/main/default/objects/RaceStatistics__c/fields/FastestSector3TimeMilliseconds__c.field-meta.xml
<CustomField>
    <fullName>FastestSector3TimeMilliseconds__c</fullName>
    <label>Sector 3 Time Milliseconds</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter11/force-app/main/default/objects/RaceStatistics__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Statistics</relationshipLabel>
    <relationshipName>Race_Statistics</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Chapter11/force-app/main/default/classes/RaceStatisticsSelector.cls
public class RaceStatisticsSelector extends ApplicationSelector {
    
	public RaceStatisticsSelector() {
		super();
	}

	public RaceStatisticsSelector(Boolean includeFieldSetFields) {
		super(includeFieldSetFields);
	}

	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			RaceStatistics__c.Id,
			RaceStatistics__c.Name,
			RaceStatistics__c.Race__c,			
            RaceStatistics__c.FastestSector1Driver__c,
            RaceStatistics__c.FastestSector1Time__c,
            RaceStatistics__c.FastestSector1TimeMilliseconds__c,
            RaceStatistics__c.FastestSector2Driver__c,
            RaceStatistics__c.FastestSector2Time__c,
            RaceStatistics__c.FastestSector2TimeMilliseconds__c,
            RaceStatistics__c.FastestSector3Driver__c,
            RaceStatistics__c.FastestSector3Time__c,
            RaceStatistics__c.FastestSector3TimeMilliseconds__c
		};
	}

	public Schema.SObjectType getSObjectType() {
		return RaceStatistics__c.sObjectType;
	}

	public List<RaceStatistics__c> selectById(Set<Id> idSet) {
        return (List<RaceStatistics__c>) selectSObjectsById(idSet);    
	}

	public List<RaceStatistics__c> selectByRaceId(Set<Id> raceIds) {
        return (List<RaceStatistics__c>) Database.query(newQueryFactory().setCondition('Race__c in :raceIds').toSOQL());
	}
}