Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter07/force-app/main/default/objects/Race__c/fields/FastestLapBy__c.field-meta.xml
<CustomField>
    <fullName>FastestLapBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fastest Lap By</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>FastestLaps</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter12/force-app/main/default/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Chapter15/force-app/main/default/classes/FLSDemoController.cls
public with sharing class FLSDemoController {

	public Race__c Race {get;set;}

	public String Status { get { return Race.Status__c; }}

	public String FastestLapBy { get { return Race.FastestLapBy__c; }}

	public FLSDemoController() 
	{
		Race = [select Status__c, FastestLapBy__c from Race__c limit 1];	
	}

	@AuraEnabled
	public static Race__c getRace(Id raceId) {
		return [select Status__c, FastestLapBy__c from Race__c where id = :raceId];
	}
}