Chapter10/force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter09/force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter14/force-app/main/default/objects/Contestant__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter08/force-app/main/default/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter08/force-app/main/default/objects/Contestant__c/fields/DNF__c.field-meta.xml
<CustomField>
    <fullName>DNF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DNF</label>
    <type>Checkbox</type>
</CustomField>

Chapter12/force-app/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Drivers who&#39;s status is active are permitted.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter07/force-app/main/default/objects/Contestant__c/fields/DriverRace__c.field-meta.xml
<CustomField>
    <fullName>DriverRace__c</fullName>
    <formula>Driver__r.Name + &#39; (&#39; + Race__r.Name + &#39;)&#39;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver and Race</label>
    <type>Text</type>
</CustomField>

Chapter13/force-app/main/default/objects/Contestant__c/fields/GridPosition__c.field-meta.xml
<CustomField>
    <fullName>GridPosition__c</fullName>
    <label>Grid Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter04/force-app/main/default/objects/Contestant__c/fields/Qualification1LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification1LapTime__c</fullName>
    <label>Qualification 1 Lap Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

Chapter10/force-app/main/default/objects/Contestant__c/fields/Qualification2LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification2LapTime__c</fullName>
    <label>Qualification 2 Lap Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

Chapter06/force-app/main/default/objects/Contestant__c/fields/Qualification3LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification3LapTime__c</fullName>
    <label>Qualification 3 Lap Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter12/force-app/main/default/objects/Contestant__c/fields/RaceTime__c.field-meta.xml
<CustomField>
    <fullName>RaceTime__c</fullName>
    <label>Race Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

Chapter11/force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter10/force-app/main/default/objects/Driver__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter14/force-app/main/default/objects/Race__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter03/force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter13/force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter07/force-app/main/default/classes/ContestantsSelector.cls
public inherited sharing class ContestantsSelector extends ApplicationSelector implements IContestantsSelector {
    
	public static IContestantsSelector newInstance()  { 
		return (IContestantsSelector) Application.Selector.newInstance(Contestant__c.SObjectType); 
	}

	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Contestant__c.Id,
			Contestant__c.Name,
			Contestant__c.ChampionshipPoints__c,
			Contestant__c.DNF__c,
			Contestant__c.Driver__c,
			Contestant__c.DriverRace__c,
			Contestant__c.GridPosition__c,
			Contestant__c.Qualification1LapTime__c,
			Contestant__c.Qualification2LapTime__c,
			Contestant__c.Qualification3LapTime__c,
			Contestant__c.Race__c,
			Contestant__c.RacePosition__c,
			Contestant__c.RaceTime__c 
		};
	}

	public Schema.SObjectType getSObjectType() {
		return Contestant__c.sObjectType;
	}

	public override String getOrderBy() {
		return 'Race__r.Season__r.Name, Race__r.Name, RacePosition__c';
	}

	public List<Contestant__c> selectById(Set<Id> ids) {
		return (List<Contestant__c>) super.selectSObjectsById(ids);
	}

	public List<Contestant__c> selectByIdWithDriver(Set<Id> driverIds) {
	    
	    fflib_QueryFactory contestantQueryFactory = newQueryFactory();
            
        new DriversSelector().
            configureQueryFactoryFields(
                contestantQueryFactory, 
                Contestant__c.Driver__c.getDescribe().getRelationshipName());
                
		return Database.query(
            contestantQueryFactory.setCondition('Id in :driverIds').toSOQL());
	}	

	public Map<Id, List<Summary>> selectByRaceIdWithContestantSummary(Set<Id> raceIds) {
	    
		Map<Id, List<Summary>> summariesByRaceId = new Map<Id, List<Summary>>();
				
		for(Contestant__c contestant : 
			Database.query(
			    newQueryFactory(false).
			        selectField(Contestant__c.RacePosition__c).
			        selectField('Race__r.Name').
                    selectField('Race__r.Season__r.Name').
                    selectField('Driver__r.Name').
                    selectField('Driver__r.Team__r.Name').
                    selectField('Car__r.Name').
			        setCondition('Race__c in :raceIds').
			        toSOQL())) {

			List<Summary> summaries = summariesByRaceId.get(contestant.Race__c);
			if(summaries==null)
				summariesByRaceId.put(contestant.Race__c, summaries = new List<Summary>());
			summaries.add(new Summary(contestant));
		}
		
		return summariesByRaceId;
	}

	public class Summary {
		private Contestant__c contestant;				
		public String Season { 
			get { return contestant.Race__r.Season__r.Name; }}		
		public String Race { 
			get { return contestant.Race__r.Name; } }	
		public Decimal Position { 
			get { return contestant.RacePosition__c; } }				
		public String Driver { 
			get { return contestant.Driver__r.Name; } }		
		public String Team { 
			get { return contestant.Driver__r.Team__r.Name; } }		
		public String Car { 
			get { return contestant.Car__r.Name; } }		
		@TestVisible			
		private Summary(Contestant__c contestant) { 
			this.contestant = contestant; }
	}
}