Chapter10/force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter13/force-app/main/default/objects/Car__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter07/force-app/main/default/classes/Cars.cls
public inherited sharing class Cars extends ApplicationDomain implements ComplianceService.ICompliant {
    
	public Cars(List<Car__c> cars) {
		super(cars);
	}

	public List<ComplianceService.VerifyResult> verifyCompliance() {
		List<ComplianceService.VerifyResult> compliances = new List<ComplianceService.VerifyResult>();
		for(Car__c car : (List<Car__c>) Records) {
			// Check weight compliance
			ComplianceService.VerifyResult license = new ComplianceService.VerifyResult();
			license.ComplianceCode = '4.1';
			license.RecordId = car.Id;
			license.passed = car.Weight__c !=null && car.Weight__c >= 691;
			license.failureReason = license.passed ? null : 'Car must not be less than 691kg.';
			compliances.add(license);
		}
		return compliances;
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable {
		public fflib_SObjectDomain construct(List<SObject> sObjectList) {
			return new Cars(sObjectList);
		}
	}
}