Chapter10/force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter09/force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter14/force-app/main/default/objects/Contestant__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter12/force-app/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Drivers who&#39;s status is active are permitted.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter11/force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter09/force-app/main/default/classes/RaceServiceImpl.cls
public inherited sharing class RaceServiceImpl implements IRaceService {
    
    public Map<Id, List<RaceService.ProvisionalResult>> calculateProvisionResults(Set<Id> raceIds) {           
        throw new RaceService.RaceServiceException('Not implemented');
    }

    public void applyRaceResults(Map<Id, List<RaceService.ProvisionalResult>> provisionalResultsByRaceId) {
        throw new RaceService.RaceServiceException('Not implemented');
    }

    public void awardChampionshipPoints(Set<Id> raceIds) {
        
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        // Query Races and contestants and bulkify list of all contestants
        List<Contestant__c> contestants = new List<Contestant__c>();
        for(Race__c race : new RacesSelector().selectByIdWithContestants(raceIds)) {
            contestants.addAll(race.Contestants__r);            
        }
        
        // Delegate to Contestant Domain class
        new Contestants(contestants).awardChampionshipPoints(uow);

        // Commit work
        uow.commitWork();
    }
    
	public String generateSummaryAsCSV(Set<Id> raceIds)
	{
		// Query summaries via custom selector method
		Map<Id, List<ContestantsSelector.Summary>> summariesByRaceId = 
			new ContestantsSelector().selectByRaceIdWithContestantSummary(raceIds);
		// Construct CSV output (note this is not a formal implementation of the CSV spec)
		String csvOutput = '';
		for(Id raceId : summariesByRaceId.keySet())
			for(ContestantsSelector.Summary raceContestantSummary : summariesByRaceId.get(raceId))
				csvOutput+= String.join(
					new Object[] { 
							raceContestantSummary.Season,
							raceContestantSummary.Race,
							raceContestantSummary.Position,
							raceContestantSummary.Driver,
							raceContestantSummary.Team,
							raceContestantSummary.Car
						} , ',') + '\r\n';
		return csvOutput;
	}
	
    public Map<Id, Integer> addDrivers(Map<Id, List<Id>> driversByRaceId) {
        
        // TODO: Provide a means to determine drivers current car for the season
        List<Car__c> cars = new CarsSelector().selectAll();
        if(cars.size()==0) {
            throw new RaceService.RaceServiceException('Must have at least one Car record in the system');          
        }        
        
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
 
        // Create Contestant__c records for each Driver for the given Race
        Map<Id, Integer> addedDriversByRace = new Map<Id, Integer>();
        for(Id raceId : driversByRaceId.keySet()) {
            for(Id driverId : driversByRaceId.get(raceId)) {
                Contestant__c contestant = new Contestant__c();
                contestant.Race__c = raceId;
                contestant.Driver__c = driverId;
                contestant.Car__c = cars[0].Id;
                uow.registerNew(contestant);                
            }
            addedDriversByRace.put(raceId, driversByRaceId.get(raceId).size());
        }       
 
        // Commit work
        uow.commitWork();
        
        return addedDriversByRace;
    }	
}