Chapter10/force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter09/force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter14/force-app/main/default/objects/Contestant__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter12/force-app/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Drivers who&#39;s status is active are permitted.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter13/force-app/main/default/objects/Contestant__c/fields/RaceDataID__c.field-meta.xml
<CustomField>
    <fullName>RaceDataID__c</fullName>
    <externalId>true</externalId>
    <label>Race Data ID</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Chapter11/force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter12/force-app/main/default/objects/Driver__c/fields/DriverId__c.field-meta.xml
<CustomField>
    <fullName>DriverId__c</fullName>
    <label>Driver Id</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter11/force-app/main/default/objects/Race__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>Season__r.Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

Chapter03/force-app/main/default/objects/RaceData__c/RaceData__c.object-meta.xml
<CustomObject>
    <label>Race Data</label>
    <nameField>
        <displayFormat>RDID-{00000000}</displayFormat>
        <label>Race Data Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Race Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter12/force-app/main/default/objects/RaceData__c/fields/Contestant__c.field-meta.xml
<CustomField>
    <fullName>Contestant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contestant</label>
    <referenceTo>Contestant__c</referenceTo>
    <relationshipLabel>Race Data</relationshipLabel>
    <relationshipName>RaceData</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter14/force-app/main/default/objects/RaceData__c/fields/DriverId__c.field-meta.xml
<CustomField>
    <fullName>DriverId__c</fullName>
    <label>Driver Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Chapter11/force-app/main/default/objects/RaceData__c/fields/Lap__c.field-meta.xml
<CustomField>
    <fullName>Lap__c</fullName>
    <label>Lap</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter09/force-app/main/default/objects/RaceData__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Data</relationshipLabel>
    <relationshipName>RaceData</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter15/force-app/main/default/objects/RaceData__c/fields/RaceName__c.field-meta.xml
<CustomField>
    <fullName>RaceName__c</fullName>
    <label>Race Name</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

Chapter12/force-app/main/default/objects/RaceData__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter14/force-app/main/default/objects/RaceData__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oil Pressure</fullName>
            </value>
            <value>
                <fullName>Engine Temperature</fullName>
            </value>
            <value>
                <fullName>Track Temperature</fullName>
            </value>
            <value>
                <fullName>Tyre Temperature</fullName>
            </value>
            <value>
                <fullName>Sector Time</fullName>
            </value>
            <value>
                <fullName>Fuel Level</fullName>
            </value>
            <value>
                <fullName>Pitstop Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
    <type>Picklist</type>
</CustomField>

Chapter15/force-app/main/default/objects/RaceData__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Chapter14/force-app/main/default/objects/RaceData__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter15/force-app/main/default/objects/RaceNewsFeed__e/RaceNewsFeed__e.object-meta.xml
<CustomObject>
    <description>Allow your race news reporters to get the very latest information when it happens!</description>
    <label>Race News Feed</label>
    <pluralLabel>Race News Feeds</pluralLabel>
</CustomObject>

Chapter12/force-app/main/default/objects/RaceNewsFeed__e/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Chapter13/force-app/main/default/objects/RaceNewsFeed__e/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Chapter13/force-app/main/default/objects/RaceStatistics__c/RaceStatistics__c.object-meta.xml
<CustomObject>
    <label>Race Statistics</label>
    <nameField>
        <displayFormat>RCS-{00000000}</displayFormat>
        <label>Race Statastics  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Race Statistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter11/force-app/main/default/objects/RaceStatistics__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Statistics</relationshipLabel>
    <relationshipName>Race_Statistics</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Chapter11/force-app/main/default/classes/RaceServiceImpl.cls
public inherited sharing class RaceServiceImpl implements IRaceService {
    
    public Map<Id, List<RaceService.ProvisionalResult>> calculateProvisionResults(Set<Id> raceIds) {           
        throw new RaceService.RaceServiceException('Not implemented');
    }

    public void applyRaceResults(Map<Id, List<RaceService.ProvisionalResult>> provisionalResultsByRaceId) {
        throw new RaceService.RaceServiceException('Not implemented');
    }

    public void awardChampionshipPoints(Set<Id> raceIds) {
        
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        // Query Races and contestants and bulkify list of all contestants
        List<Contestant__c> contestants = new List<Contestant__c>();
        for(Race__c race : new RacesSelector().selectByIdWithContestants(raceIds)) {
            contestants.addAll(race.Contestants__r);            
        }
        
        // Delegate to Contestant Domain class
        new Contestants(contestants).awardChampionshipPoints(uow);

        // Send event notifying the press that the results are published
        uow.registerNew(
            new RaceNewsFeed__e(
                Category__c = 'Race News', 
                Content__c = 'Championship points have been officially calculated'));

        // Commit work
        uow.commitWork();
    }
    
	public String generateSummaryAsCSV(Set<Id> raceIds)
	{
		// Query summaries via custom selector method
		Map<Id, List<ContestantsSelector.Summary>> summariesByRaceId = 
			new ContestantsSelector().selectByRaceIdWithContestantSummary(raceIds);
		// Construct CSV output (note this is not a formal implementation of the CSV spec)
		String csvOutput = '';
		for(Id raceId : summariesByRaceId.keySet())
			for(ContestantsSelector.Summary raceContestantSummary : summariesByRaceId.get(raceId))
				csvOutput+= String.join(
					new Object[] { 
							raceContestantSummary.Season,
							raceContestantSummary.Race,
							raceContestantSummary.Position,
							raceContestantSummary.Driver,
							raceContestantSummary.Team,
							raceContestantSummary.Car
						} , ',') + '\r\n';
		return csvOutput;
	}
	
    public Map<Id, Integer> addDrivers(Map<Id, List<Id>> driversByRaceId) {
        
        // TODO: Provide a means to determine drivers current car for the season
        List<Car__c> cars = new CarsSelector().selectAll();
        if(cars.size()==0) {
            throw new RaceService.RaceServiceException('Must have at least one Car record in the system');          
        }        
        
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
 
        // Create Contestant__c records for each Driver for the given Race
        Map<Id, Integer> addedDriversByRace = new Map<Id, Integer>();
        for(Id raceId : driversByRaceId.keySet()) {
            for(Id driverId : driversByRaceId.get(raceId)) {
                Contestant__c contestant = new Contestant__c();
                contestant.Race__c = raceId;
                contestant.Driver__c = driverId;
                contestant.Car__c = cars[0].Id;
                uow.registerNew(contestant);                
            }
            addedDriversByRace.put(raceId, driversByRaceId.get(raceId).size());
        }       
 
        // Commit work
        uow.commitWork();
        
        return addedDriversByRace;
    }	

	public Id runProcessDataJob()
	{
		// TODO: Implement concurrency check and scope config (via custom setting)
		return Database.executeBatch(new ProcessRaceDataJob(), 2000);	
	}    
    
	public void processData(Set<Id> raceDataIds)
	{
		// Query Race Data records and update with Contestant relationship
		fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		for(RaceData__c raceData : 
				(List<RaceData__c>)
					Application.Selector.selectById(raceDataIds))
		{
			// Associate Race Data record with a Contestant via Unique Id
			raceData.Contestant__r = 
				new Contestant__c(
					RaceDataId__c = 
						Contestants.makeRaceDataId(
							raceData.Year__c, 
							raceData.RaceName__c, 
							raceData.DriverId__c));
			uow.registerDirty(raceData);
		}
		// Update records
		uow.commitWork();
	}
        
	public List<RaceService.AnalysisResult> analizeData(Set<String> raceNames)
	{
		// Sample code to illustrate unbounded queries in Chatper 11
		List<RaceData__c> raceData = 
			RaceDataSelector.newInstance().selectByRaceName(raceNames);			
		return null;
	}

	/**
	 * Optimally ingests raw external telemetry for the currently active race
	 */
    public void ingestTelemetry(List<RaceService.Telemetry> telemetry) {
		Integer currentYear = 2019; // Hard coded for this sample code Chapter 11
		String currentRaceName = 'Spain'; // Hard coded for this sample code Chapter 11
		fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		for(RaceService.Telemetry incommingData : telemetry) {
			RaceData__c raceData = new RaceData__c();
			raceData.Year__c = currentYear;
			raceData.RaceName__c = currentRaceName;
			raceData.DriverId__c = incommingData.DriverId;
			raceData.Lap__c = incommingData.Lap;
			raceData.Sector__c = incommingData.Sector;
			raceData.Type__c = incommingData.Type;
			raceData.Value__c = incommingData.Value;
			raceData.Contestant__r = 
				new Contestant__c(
					RaceDataId__c = 
						Contestants.makeRaceDataId(
							raceData.Year__c, 
							raceData.RaceName__c, 
							raceData.DriverId__c));
			uow.registerNew(raceData);
		}	
		uow.commitWork();	
	}

	/**
	 * Updates various persistant stats based on telemetry for known contestants
	*/
	public void processTelemetry(List<RaceService.ContestantResolvedTelemetry> telemetry) {

		// Query contestants to obtain their related races
		Set<Id> contestantIds = new Set<Id>();
		for(RaceService.ContestantResolvedTelemetry event : telemetry) {
			contestantIds.add(event.ContestantId);
		}
		Map<Id,Id> racesByContestantId = new Map<Id,Id>();
		for(Contestant__c contestant : new ContestantsSelector().selectById(contestantIds)) {
			racesByContestantId.put(contestant.Id, contestant.Race__c);
		}
		// Query the current Race Statistics
		Map<Id, RaceStatistics__c> statsByRaceId = new Map<Id, RaceStatistics__c>();
		for(RaceStatistics__c stat : new RaceStatisticsSelector().selectByRaceId( new Set<Id>(racesByContestantId.values()))) {
			statsByRaceId.put(stat.Race__c, stat);
		}

		// Adjust stats accordingly
		fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();		
		for(RaceService.ContestantResolvedTelemetry event : telemetry) {
			Id raceId = racesByContestantId.get(event.ContestantId);
			RaceStatistics__c stat = statsByRaceId.get(raceId);
			if(stat==null) {
				stat = new RaceStatistics__c();
				stat.Race__c = raceId;
			}
			// New fastest sector time?
			if(event.Type == 'Sector Time') {
				Decimal currentSectorTime = (Decimal) stat.get('FastestSector'+event.Sector+'TimeMilliseconds__c');
				if(currentSectorTime == null || event.Value < currentSectorTime) {
					stat.put('FastestSector'+event.Sector+'TimeMilliseconds__c', event.Value);
					stat.put('FastestSector'+event.Sector+'Time__c', String.valueOf(Time.newInstance(0,0,0,Integer.valueOf(event.Value))));
					stat.put('FastestSector'+event.Sector+'Driver__c', ''+event.ContestantId);
					uow.registerUpsert(stat);
				}
			}
		}
		uow.commitWork();
	}
}