Chapter10/force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter09/force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter14/force-app/main/default/objects/Contestant__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter12/force-app/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Drivers who&#39;s status is active are permitted.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter11/force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter10/force-app/main/default/objects/Driver__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter14/force-app/main/default/objects/Race__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter03/force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter13/force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter14/force-app/main/default/classes/RaceSummaryControllerTest.cls
@IsTest
private class RaceSummaryControllerTest  {
    
	private static Id TEST_RACE_ID = fflib_IDGenerator.generate(Race__c.SObjectType);

	@IsTest
	private static void testLoadSummaries() {
	    
		// Set mock implementation of ContestantsSelector
		Application.Selector.setMock(new ContestantsSelectorMock());

		// Invoke controller method to load summaries
		RaceSummaryController controller = 
			new RaceSummaryController(
				new ApexPages.StandardController(
					new Race__c(Id = TEST_RACE_ID)));
		PageReference pageRef = controller.loadSummary();

		// Assert view state from controller
		System.assertEquals(null, pageRef);
		System.assertEquals(1, controller.Summary.size());
		System.assertEquals('2014', controller.Summary[0].Season);
		System.assertEquals('Spa', controller.Summary[0].Race);
		System.assertEquals(1,  controller.Summary[0].Position);
		System.assertEquals('Lewis Hamilton', controller.Summary[0].Driver);
		System.assertEquals('Mercedes', controller.Summary[0].Team);
		System.assertEquals('MP4-29', controller.Summary[0].Car);
	}

	public class ContestantsSelectorMock implements IContestantsSelector {
	    
		public Map<Id, List<ContestantsSelector.Summary>> selectByRaceIdWithContestantSummary(Set<Id> raceIds)
		{
			// Assert this is our test Race ID
			Id raceId = (Id) raceIds.iterator().next();
			System.assertEquals(TEST_RACE_ID, raceId);

			// Create mock data record
			Contestant__c contestant = new Contestant__c();
			contestant.RacePosition__c = 1;
			contestant.Race__r = 
				new Race__c(Name = 'Spa',
					Season__r = 
						new Season__c(Name = '2014'));
			contestant.Driver__r = 
				new Driver__c(Name = 'Lewis Hamilton',
					Team__r = 
						new Team__c(Name = 'Mercedes'));
			contestant.Car__r = 
				new Car__c(Name = 'MP4-29');

			// Return mock response
			return new Map<Id, List<ContestantsSelector.Summary>> 
				{ raceId => new List<ContestantsSelector.Summary> { 
					new ContestantsSelector.Summary(contestant) } };
		}
		
        public Schema.SObjectType sObjectType() {
            return Contestant__c.SObjectType;
        }
        public List<SObject> selectSObjectsById(Set<Id> idSet) {
            throw new ContestantsSelectorMockException('Not implemented');
        }    		
	}
	
	public class ContestantsSelectorMockException extends Exception {}
}