Chapter10/force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter13/force-app/main/default/objects/Car__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter15/force-app/main/default/classes/CarsSelector.cls
public inherited sharing class CarsSelector extends ApplicationSelector 
{
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Car__c.Id,
			Car__c.Name,
			Car__c.Weight__c
		};
	}

	public Schema.SObjectType getSObjectType() {
		return Car__c.sObjectType;
	}
		
    public List<Car__c> selectAll() {
        return (List<Car__c>) 
           Database.query(
               newQueryFactory().toSOQL());        
    }		
}