Chapter09/force-app/main/default/objects/ChampionshipPoint__mdt/ChampionshipPoint__mdt.object-meta.xml
<CustomObject>
    <label>Championship Point</label>
    <pluralLabel>Championship Points</pluralLabel>
</CustomObject>

Chapter09/force-app/main/default/objects/ChampionshipPoint__mdt/fields/PointsAwarded__c.field-meta.xml
<CustomField>
    <fullName>PointsAwarded__c</fullName>
    <label>Points Awarded</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter09/force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter08/force-app/main/default/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter08/force-app/main/default/objects/Contestant__c/fields/DNF__c.field-meta.xml
<CustomField>
    <fullName>DNF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DNF</label>
    <type>Checkbox</type>
</CustomField>

Chapter12/force-app/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Drivers who&#39;s status is active are permitted.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter11/force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter12/force-app/main/default/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Chapter10/force-app/main/default/classes/Contestants.cls
public inherited sharing class Contestants extends ApplicationDomain {

	public Contestants(List<Contestant__c> contestants) {
		super(contestants);
	}

    /** 
     * Performas validation on insert of new Contestants
     **/
	public override void onValidate() {	    
		// Bulk load the associated races
		Set<Id> raceIds = new Set<Id>();
		for(Contestant__c contestant : (List<Contestant__c>) Records) {
            raceIds.add(contestant.Race__c);		    
		}
		Map<Id, Race__c> associatedRaces = 
			new Map<Id, Race__c>(new RacesSelector().selectById(raceIds));

		// Only permit new contestants to be added to Scheduled races, unless they have race position or DNF (aka historic data load)
		for(Contestant__c contestant : (List<Contestant__c>) Records) {
			Race__c race = associatedRaces.get(contestant.Race__c);
			if(race.Status__c != 'Scheduled' && contestant.RacePosition__c == null && contestant.DNF__c != true) {
                contestant.addError( 'Contestants can only be added to scheduled races');			    
			}
		}
	}

	/**
	 * Performs validation on update of existing Contestants
	 **/
	public override void onValidate(Map<Id,SObject> existingRecords) {	    
		// Only validate records where the Driver has been changed
		List<Contestant__c> changedDrivers = 
			getChangedRecords(
				new Set<SObjectField> { Contestant__c.Driver__c });
		// Bulk load the associated races
		Map<Id, Race__c> associatedRaces = queryAssociatedRaces(changedDrivers);
		// Can only change drivers in scheduled races
		for(Contestant__c contestant : changedDrivers) { 
			Race__c contestantRace = associatedRaces.get(contestant.Race__c);
			if(contestantRace.Status__c != 'Scheduled') {
                contestant.Driver__c.addError( 'You can only change drivers for scheduled races' );			       
            }
		}
	}

    /**
     * Awards the applicable championship points to the contestants
     **/
	public void awardChampionshipPoints(fflib_ISObjectUnitOfWork uow) {

		// Custom implementation configured by Developer X?
		Object registeredInterfaceImpl = 
		    Application.Callouts.newInstance(ContestantService.IAwardChampionshipPoints.class);
		if(registeredInterfaceImpl instanceof ContestantService.IAwardChampionshipPoints) {
			// Cast the interface to call the calculate method
			ContestantService.IAwardChampionshipPoints awardChampionshipPoints = 
				(ContestantService.IAwardChampionshipPoints) registeredInterfaceImpl;
			// Invoke the custom method from Developer X
			awardChampionshipPoints.calculate(Records);
			// Mark dirty on behalf of Developer X
			for(Contestant__c contestant : (List<Contestant__c>) Records) {
                uow.registerDirty(contestant);			    
			}
			return;
		}

        // Apply championship points to given contestants
        Map<Integer, ChampionshipPoint__mdt> pointsByTrackPosition = 
          new ChampionshipPointsSelector().selectAllByTrackPosition();      
        for(Contestant__c contestant : (List<Contestant__c>) Records) {
            // Determine points to award for the given position
            ChampionshipPoint__mdt pointsForPosition = 
                pointsByTrackPosition.get(Integer.valueOf(contestant.RacePosition__c));
            if(pointsForPosition!=null) {
                // Apply points and register for udpate with uow
                contestant.ChampionshipPoints__c = pointsForPosition.PointsAwarded__c;
                uow.registerDirty(contestant);
            }
        }       
	}

	private Map<Id, Race__c> queryAssociatedRaces(List<Contestant__c> contestants) {
		// Bulk load the associated races
		Set<Id> raceIds = new Set<Id>();
		for(Contestant__c contestant : contestants) {
            raceIds.add(contestant.Race__c);		    
		}			
		return new Map<Id, Race__c>(new RacesSelector().selectById(raceIds));		
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable {
		public fflib_SObjectDomain construct(List<SObject> sObjectList) {
			return new Contestants(sObjectList);
		}
	}	
}