Chapter09/force-app/main/default/objects/ChampionshipPoint__mdt/ChampionshipPoint__mdt.object-meta.xml
<CustomObject>
    <label>Championship Point</label>
    <pluralLabel>Championship Points</pluralLabel>
</CustomObject>

Chapter09/force-app/main/default/objects/ChampionshipPoint__mdt/fields/PointsAwarded__c.field-meta.xml
<CustomField>
    <fullName>PointsAwarded__c</fullName>
    <label>Points Awarded</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter09/force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter08/force-app/main/default/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter05/force-app/main/default/classes/ContestantService.cls
public with sharing class ContestantService {
       
	public static void awardChampionshipPoints(Set<Id> contestantIds) {
	    
		// Apply championship points to selected contestants		
		fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
		awardChampionshipPoints(uow, new ContestantsSelector().selectById(contestantIds));
		uow.commitWork();
	}

	public static void awardChampionshipPoints(fflib_ISObjectUnitOfWork uow, List<Contestant__c> contestants) {
	    
		// Apply championship points to given contestants
		Map<Integer, ChampionshipPoint__mdt> pointsByTrackPosition = 
		  new ChampionshipPointsSelector().selectAllByTrackPosition();		
		for(Contestant__c contestant : contestants) {
			// Determine points to award for the given position
			ChampionshipPoint__mdt pointsForPosition = 
                pointsByTrackPosition.get(Integer.valueOf(contestant.RacePosition__c));
			if(pointsForPosition!=null) {
				// Apply points and register for udpate with uow
				contestant.ChampionshipPoints__c = pointsForPosition.PointsAwarded__c;
				uow.registerDirty(contestant);
			}
		}		
	}

	public static void retireFromRace(List<RaceRetirement> retirements) {
		throw new ContestantServiceException('Not implemented');
	}

	public class ContestantServiceException extends Exception {} 

	public class RaceRetirement {
		public Id contestantId;
		public String reason;
	}	
}