Chapter14/force-app/main/default/objects/Callout__mdt/Callout__mdt.object-meta.xml
<CustomObject>
    <label>Callout</label>
    <pluralLabel>Callouts</pluralLabel>
</CustomObject>

Chapter11/force-app/main/default/objects/Callout__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

Chapter14/force-app/main/default/objects/Callout__mdt/fields/ApexClassNamespacePrefix__c.field-meta.xml
<CustomField>
    <fullName>ApexClassNamespacePrefix__c</fullName>
    <label>Apex Class Namespace Prefix</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

Chapter15/force-app/main/default/objects/Callout__mdt/fields/InterfaceType__c.field-meta.xml
<CustomField>
    <fullName>InterfaceType__c</fullName>
    <label>Interface Type</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Chapter13/force-app/main/default/classes/CalloutsSelector.cls
public class CalloutsSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Callout__mdt.Id,
            Callout__mdt.DeveloperName,
            Callout__mdt.NamespacePrefix,
            Callout__mdt.ApexCLass__c,
            Callout__mdt.ApexCLassNamespacePrefix__c,
            Callout__mdt.InterfaceType__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Callout__mdt.sObjectType;
    }
    
    public Map<Type, Type> selectAllCallouts() {        
        // Query custom metadata records for callouts
        Map<Type, Type> calloutsByInterfaceType = new Map<Type, Type>();                    
        for(Callout__mdt record : Database.query(newQueryFactory().toSOQL())) {
            if(Callout__mdt.ApexCLass__c!=null) {
                // Namespace of the interface is that of the custom metadata type 
                Type interfaceType = Type.forName(record.NamespacePrefix, record.InterfaceType__c);
                // Implementing class can optionally specify  the namespace if needed
                Type implType = Type.forName(record.ApexCLassNamespacePrefix__c, record.ApexCLass__c);
                calloutsByInterfaceType.put(interfaceType, implType);
            }
        }       
        return calloutsByInterfaceType;
    }
}