Chapter09/force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter08/force-app/main/default/objects/Contestant__c/fields/DNF__c.field-meta.xml
<CustomField>
    <fullName>DNF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DNF</label>
    <type>Checkbox</type>
</CustomField>

Chapter12/force-app/main/default/classes/OutOfRaceController.cls
public with sharing class OutOfRaceController 
{
	private ApexPages.StandardSetController standardSetController;

	public OutOfRaceController(ApexPages.StandardSetController standardSetController) 
	{
		this.standardSetController = standardSetController;		
	}

	public PageReference markAsDNF()
	{
		for(Contestant__c contestant : (List<Contestant__c>) standardSetController.getSelected())
			contestant.DNF__c = true;		
		return null;
	}
}