Chapter09/force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter08/force-app/main/default/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter08/force-app/main/default/objects/Contestant__c/fields/DNF__c.field-meta.xml
<CustomField>
    <fullName>DNF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DNF</label>
    <type>Checkbox</type>
</CustomField>

Chapter12/force-app/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Drivers who&#39;s status is active are permitted.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter07/force-app/main/default/objects/Contestant__c/fields/DriverRace__c.field-meta.xml
<CustomField>
    <fullName>DriverRace__c</fullName>
    <formula>Driver__r.Name + &#39; (&#39; + Race__r.Name + &#39;)&#39;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver and Race</label>
    <type>Text</type>
</CustomField>

Chapter13/force-app/main/default/objects/Contestant__c/fields/GridPosition__c.field-meta.xml
<CustomField>
    <fullName>GridPosition__c</fullName>
    <label>Grid Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter04/force-app/main/default/objects/Contestant__c/fields/Qualification1LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification1LapTime__c</fullName>
    <label>Qualification 1 Lap Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

Chapter10/force-app/main/default/objects/Contestant__c/fields/Qualification2LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification2LapTime__c</fullName>
    <label>Qualification 2 Lap Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

Chapter06/force-app/main/default/objects/Contestant__c/fields/Qualification3LapTime__c.field-meta.xml
<CustomField>
    <fullName>Qualification3LapTime__c</fullName>
    <label>Qualification 3 Lap Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter12/force-app/main/default/objects/Contestant__c/fields/RaceTime__c.field-meta.xml
<CustomField>
    <fullName>RaceTime__c</fullName>
    <label>Race Time</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

Chapter11/force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter05/force-app/main/default/classes/ContestantsSelector.cls
public inherited sharing class ContestantsSelector extends fflib_SObjectSelector {
    
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Contestant__c.Id,
			Contestant__c.Name,
			Contestant__c.ChampionshipPoints__c,
			Contestant__c.DNF__c,
			Contestant__c.Driver__c,
			Contestant__c.DriverRace__c,
			Contestant__c.GridPosition__c,
			Contestant__c.Qualification1LapTime__c,
			Contestant__c.Qualification2LapTime__c,
			Contestant__c.Qualification3LapTime__c,
			Contestant__c.Race__c,
			Contestant__c.RacePosition__c,
			Contestant__c.RaceTime__c 
		};
	}

	public Schema.SObjectType getSObjectType() {
		return Contestant__c.sObjectType;
	}

	public List<Contestant__c> selectById(Set<Id> ids) {
		return (List<Contestant__c>) super.selectSObjectsById(ids);
	}
}