Chapter09/force-app/main/default/objects/Contestant__c/Contestant__c.object-meta.xml
<CustomObject>
    <label>Contestant</label>
    <nameField>
        <displayFormat>CONTESTANT-{00000000}</displayFormat>
        <label>Contestant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contestants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter08/force-app/main/default/objects/Contestant__c/fields/ChampionshipPoints__c.field-meta.xml
<CustomField>
    <fullName>ChampionshipPoints__c</fullName>
    <label>Championship Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter12/force-app/main/default/objects/Contestant__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Drivers can be contestants in a race.</errorMessage>
        <filterItems>
            <field>Driver__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Only Drivers who&#39;s status is active are permitted.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <type>Lookup</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Contestants</relationshipLabel>
    <relationshipName>Contestants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter05/force-app/main/default/objects/Contestant__c/fields/RacePosition__c.field-meta.xml
<CustomField>
    <fullName>RacePosition__c</fullName>
    <label>Race Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter11/force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter12/force-app/main/default/objects/Driver__c/fields/DriverId__c.field-meta.xml
<CustomField>
    <fullName>DriverId__c</fullName>
    <label>Driver Id</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Chapter12/force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Chapter14/force-app/main/default/objects/Race__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Chapter12/force-app/main/default/objects/Race__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Red Flagged</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Chapter11/force-app/main/default/objects/Race__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>Season__r.Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

Chapter03/force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter10/force-app/main/default/objects/Season__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <externalId>true</externalId>
    <label>Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Chapter08/force-app/main/default/classes/ContestantsTest.cls
@IsTest
private class ContestantsTest 
{
	@IsTest
	private static void testAddContestantNoneScheduled()
	{
		// Test data
		Season__c season = new Season__c(Name = '2014', Year__c = '2014');
		insert season;
		Driver__c driver = new Driver__c(Name = 'Lewis Hamilton', DriverId__c = '42');
		insert driver;
		Race__c race = new Race__c(Name = 'Spa', Status__c  = 'In Progress', Season__c = season.Id);
		insert race;

		Test.startTest();
		try 
		{
			// Insert Contestant to In Progress race
			Contestant__c contestant = new Contestant__c(Driver__c = driver.Id, Race__c = race.Id);
			insert contestant;
			System.assert(false, 'Expected exception');
		}
		catch (DMLException e)
		{
			System.assertEquals(1, e.getNumDml());
			System.assertEquals('Contestants can only be added to scheduled races', e.getDmlMessage(0));
			System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDmlType(0));
		}
		Test.stopTest();
	}

	@IsTest
	private static void testChangeContestantNoneScheduled()
	{
		// Test data
		Season__c season = new Season__c(Name = '2014', Year__c = '2014');
		insert season;
		Driver__c driver = new Driver__c(Name = 'Lewis Hamilton', DriverId__c = '42');
		insert driver;
		Driver__c anotherDriver = new Driver__c(Name = 'A Another', DriverId__c = '43');
		insert anotherDriver;
		Race__c race = new Race__c(Name = 'Spa', Status__c  = 'Scheduled', Season__c = season.Id);
		insert race;
		Contestant__c contestant = new Contestant__c(Driver__c = driver.Id, Race__c = race.Id);
		insert contestant;
		race.Status__c = 'In Progress';
		update race;

		Test.startTest();
		try
		{
			contestant.Driver__c = anotherDriver.Id;
			update contestant;
		}
		catch (DmlException e)
		{
			System.assertEquals(1, e.getNumDml());
			System.assertEquals('You can only change drivers for scheduled races', e.getDmlMessage(0));
			System.assertEquals(Contestant__c.Driver__c, e.getDmlFields(0)[0]);
			System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, e.getDmlType(0));
		}
		Test.stopTest();

	}

	@IsTest
	private static void testAddChampionshipPoints()
	{
		// Test data
		Season__c season = new Season__c(Name = '2014', Year__c = '2014');
		insert season;
		Driver__c driver = new Driver__c(Name = 'Lewis Hamilton', DriverId__c = '42');
		insert driver;
		Race__c race = new Race__c(Name = 'Spa', Status__c  = 'Scheduled', Season__c = season.Id);
		insert race;
		Contestant__c contestant = new Contestant__c(Driver__c = driver.Id, Race__c = race.Id);
		insert contestant;
		race.Status__c = 'Finished';
		update race;
		contestant.RacePosition__c = 1;
		update contestant;

		Test.startTest();
		Contestants contestants = new Contestants(new List<Contestant__c> { contestant });
		contestants.awardChampionshipPoints(Application.UnitOfWork.newInstance());
		System.assertEquals(25, ((Contestant__c) contestants.Records[0]).ChampionshipPoints__c);
		Test.stopTest();
	}
}