Chapter03/force-app/main/default/objects/RaceData__c/RaceData__c.object-meta.xml
<CustomObject>
    <label>Race Data</label>
    <nameField>
        <displayFormat>RDID-{00000000}</displayFormat>
        <label>Race Data Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Race Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Chapter14/force-app/main/default/objects/RaceData__c/fields/DriverId__c.field-meta.xml
<CustomField>
    <fullName>DriverId__c</fullName>
    <label>Driver Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Chapter11/force-app/main/default/objects/RaceData__c/fields/Lap__c.field-meta.xml
<CustomField>
    <fullName>Lap__c</fullName>
    <label>Lap</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter15/force-app/main/default/objects/RaceData__c/fields/RaceName__c.field-meta.xml
<CustomField>
    <fullName>RaceName__c</fullName>
    <label>Race Name</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

Chapter12/force-app/main/default/objects/RaceData__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter14/force-app/main/default/objects/RaceData__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oil Pressure</fullName>
            </value>
            <value>
                <fullName>Engine Temperature</fullName>
            </value>
            <value>
                <fullName>Track Temperature</fullName>
            </value>
            <value>
                <fullName>Tyre Temperature</fullName>
            </value>
            <value>
                <fullName>Sector Time</fullName>
            </value>
            <value>
                <fullName>Fuel Level</fullName>
            </value>
            <value>
                <fullName>Pitstop Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
    <type>Picklist</type>
</CustomField>

Chapter15/force-app/main/default/objects/RaceData__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Chapter14/force-app/main/default/objects/RaceData__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Chapter13/force-app/main/default/classes/RaceDataSelector.cls
public class RaceDataSelector extends ApplicationSelector {
    
	public static RaceDataSelector newInstance() { 
		return (RaceDataSelector) Application.Selector.newInstance(RaceData__c.SObjectType); 
	}

	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
				RaceData__c.Id,
				RaceData__c.Name,
				RaceData__c.Year__c,
				RaceData__c.RaceName__c,
				RaceData__c.Lap__c,
				RaceData__c.Sector__c,
				RaceData__c.Type__c,
				RaceData__c.Value__c,
				RaceData__c.DriverId__c
			};
	}

	public Schema.SObjectType getSObjectType() {
		return RaceData__c.sObjectType;
	}

	public List<RaceData__c> selectById(Set<ID> idSet) {
		return (List<RaceData__c>) selectSObjectsById(idSet);
	}	

	public List<RaceData__c> selectByRaceName(Set<String> raceNames) {
		return Database.query(newQueryFactory().setCondition('RaceName__c in :raceNames').toSOQL());
	}	

	public Database.QueryLocator selectAllQueryLocator() {
		return Database.getQueryLocator(newQueryFactory().toSOQL());
	}

	public List<Analysis> selectAnaysisGroupByRaceName() {
		List<Analysis> raceAnalysis = new List<Analysis>();
		for(AggregateResult result : 
			[select 
				RaceName__c raceName, Type__c type,
				AVG(Value__c) averageValue,
				MAX(Value__c) maxValue,
				MIN(Value__c) minValue
			 from RaceData__c
			 group by RaceName__c, Type__c ]) {
            raceAnalysis.add(new Analysis(result));			     
        }
		return raceAnalysis;
	}

	public class Analysis {
		private AggregateResult result;				
		public String Race { 
			get { return (String) result.get('raceName'); } }	
		public String Type { 
			get { return (String) result.get('type'); } }	
		public Decimal AverageValue { 
			get { return (Decimal) result.get('averageValue'); } }	
		public Decimal MaxValue { 
			get { return (Decimal) result.get('maxValue'); } }	
		public Decimal MinValue { 
			get { return (Decimal) result.get('minValue'); } }	
		private Analysis(AggregateResult result) { 
			this.result = result; }		
	}
}